// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC04u3_vuyTZvqjuz0CTrwTslBcs9aS39Y',
    appId: '1:1016770865093:web:b19a311d4b6eb140910dac',
    messagingSenderId: '1016770865093',
    projectId: 'frigoservicios-48cc0',
    authDomain: 'frigoservicios-48cc0.firebaseapp.com',
    storageBucket: 'frigoservicios-48cc0.firebasestorage.app',
    measurementId: 'G-EFXG8Y0X9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK9VE7OKWJ2uUZY1SV-Ad0tKXf2w6UOzI',
    appId: '1:1016770865093:android:cdaee538d80cae11910dac',
    messagingSenderId: '1016770865093',
    projectId: 'frigoservicios-48cc0',
    storageBucket: 'frigoservicios-48cc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnzvVok5pLRZo-ge1H0EPoGh0A3_8U3-4',
    appId: '1:1016770865093:ios:e1653960ce708a95910dac',
    messagingSenderId: '1016770865093',
    projectId: 'frigoservicios-48cc0',
    storageBucket: 'frigoservicios-48cc0.firebasestorage.app',
    iosBundleId: 'com.example.proyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnzvVok5pLRZo-ge1H0EPoGh0A3_8U3-4',
    appId: '1:1016770865093:ios:e1653960ce708a95910dac',
    messagingSenderId: '1016770865093',
    projectId: 'frigoservicios-48cc0',
    storageBucket: 'frigoservicios-48cc0.firebasestorage.app',
    iosBundleId: 'com.example.proyecto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC04u3_vuyTZvqjuz0CTrwTslBcs9aS39Y',
    appId: '1:1016770865093:web:2f0f56aa2b443b78910dac',
    messagingSenderId: '1016770865093',
    projectId: 'frigoservicios-48cc0',
    authDomain: 'frigoservicios-48cc0.firebaseapp.com',
    storageBucket: 'frigoservicios-48cc0.firebasestorage.app',
    measurementId: 'G-DPMY690B99',
  );
}
